### ISSUE TITLE
Pagination is off on the language pages

### ISSUE THREAD

**Issue by mikemcbride** [jakecoffman/stldevs-sapper#3]
It starts at 0 and ends at 1 minus the last page length:

<img width="172" alt="image" src="https://user-images.githubusercontent.com/6248612/108915698-e33ea100-75f2-11eb-85bf-05836540943d.png">

Wasn't sure if this was in the API or UI, but if it's here I'd be happy to take a crack at it, let me know!

**Comment by mikemcbride** [comment]
Ok I think I see what's going on. Looks like maybe the API pagination is 0 indexed but the UI is calculating total page count differently? I think I see where it's happening, I'll get a PR out when I have a chance

**Comment by jakecoffman** [comment]
This was a subtle joke about indexes starting at 0 but I see things may have gone wrong. 😆

**Comment by mikemcbride** [comment]
Hey if you like it then lets keep it at 0 - I think we would just need to update the total page count in this case? Otherwise you get to page 3 out of 4 but can't go forward. Open to your suggestions here, I do like the 0 index joke :)

**Comment by jakecoffman** [comment]
Ok the main problem is fixed by https://github.com/jakecoffman/stldevs/commit/045b2dca67722167d33bd5b2cf0dae55489cde4e. 

For some reason I decided to make a separate query to count the results?! And naturally it was getting a different result...

Anyway now I just need to fix the off by one error. Thanks for reporting this!

**Comment by mikemcbride** [comment]
Sure thing! I can take a stab at the off by one. I was looking earlier today and I think I see where it's happening. If you're cool with it I'll put up a PR

**Comment by jakecoffman** [comment]
I think I fixed it? If not feel free! PRs always welcome.

**Comment by mikemcbride** [comment]
Oh, yep! That's where I was looking too. I initially thought that commit was from the API, my bad!
